class AssertionError < Error {}
fun assert(expr, msg = "failed assertion") {
  if (!expr) {
    throw AssertionError(msg);
  }
}
