class MyError < Error { }
fun doThrow() {
  throw MyError();
}
try {
  print nil;
} catch (MyError e) {
  print e;
  e;
}
doThrow();
