class Mine {
  class Err < Error {}
}

try {
  throw Mine::Err("msg");
} catch (Mine::Err err) {
  print "caught";
}

__END__
-- expect: --
caught
